### PR TITLE
Fixes an issue when using vault with HTTPS (tls 1.2)

### PR DESCRIPTION
**Pull request by thecodeassassin**
Had to wrap curl because the python version shipped with ansible doesn't support ssl.PROTOCOL_TLSv1_2

### CODE REVIEW

**Comment by thecodeassassin** [comment]
@jhaals can you take a look at this please ? :)

**Comment by cheekyhalf** [comment]
Rather than calling out to curl why not use pycurl?

For example:

``` python
request_url = urljoin(url, "v1/%s" % (key))
buffer = StringIO()
c = pycurl.Curl()
c.setopt(c.URL, request_url)
c.setopt(c.HTTPHEADER, ['X-Vault-Token: ' + token])
c.setopt(c.WRITEDATA, buffer)
c.perform()
c.close()
result = json.loads(buffer.getvalue())
```

**Comment by thecodeassassin** [comment]
@cheekyhalf because i think adding another dependency is not a good idea
plus it doesn't add any real value here.

**Comment by jhaals** [comment]
I'm not sure this is the right thing to do.
Python is not shipped with ansible and `PROTOCOL_TLSv1_2` is supported in python 2.7.9(released in 2014) see [docs](https://docs.python.org/2/library/ssl.html#ssl.PROTOCOL_TLSv1_2). So solution to this problem would be upgrading to a newer version of python.

**Comment by thecodeassassin** [comment]
@jhaals on OSX it is... and i checked the python docs i see that it's supported since 2.7.9. But that would still not work on the version that is installed on OSX. This solution will work cross platform.

**Comment by thecodeassassin** [comment]
@jhaals but now there is still an issue with the plugin, the problem is not solved yet.

**Comment by jhaals** [comment]
I'm running Python 2.7.11 on OS X and I don't see the problem there.
What's the other issue?

**Comment by thecodeassassin** [comment]
@jhaals did you test with vault running on HTTPS with a certificate and the following modification (to use the proper TLS version):

```
            if "https" in url:
                context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
                headers = { 'X-Vault-Token' : token }
                req = urllib2.Request(request_url, None, headers)
                response = urllib2.urlopen(req, context)
                output = response.read()
```

**Comment by jhaals** [comment]
I run vault over HTTPS just supporting TLS 1.2

**Pull request closed without merging**
