### PR TITLE
added Troublshooting section

### PR DESCRIPTION
**Pull request by hilt86**
Adds a work around to resolve the error "Error was sequence item 0: expected string, dict found"

### CODE REVIEW

**Comment by hilt86** [comment]
@jhaals can we merge this please?

**Comment by jhaals** [comment]
Absolutely! 

Would you please be so kind and update the markdown format for your links. It should be 
```markdown
[text](http://url)
```

**Comment by hilt86** [comment]
Done. I am a little confused as most of the links in the content you created are formatted as [`link comment`]...

**Comment by jhaals** [comment]
👍

**Pull request merged**
