### PR TITLE
add a field parameter

### PR DESCRIPTION
**Pull request by cheekyhalf**
Simple change to make the field selectable rather than being hardcoded to 'value'

### CODE REVIEW

**Comment by jhaals** [comment]
@cheekyhalf thanks for the PR! I'm glad to see that it's backwards compatible. I wonder if it's worth going the extra mile and add support for multiple return values. 
That would allow us to use dynamic backends such as AWS which returns both `access_key` and `secret_key`. See https://www.vaultproject.io/intro/getting-started/dynamic-secrets.html

**Comment by cheekyhalf** [comment]
No problem. It already will return multiple values. If you don't supply a field you get a dictionary containing all the key/values returned by vault for that path. Because of this it isn't exactly backwards compatible..

**Comment by jhaals** [comment]
Oh right, I missed that your returning `data` straight away

**Comment by thecodeassassin** [comment]
@jhaals @cheekyhalf  this will cause an unexpected exception because you are not checking if result['data'] exists:

```
    if 'data' not in result:
            raise AnsibleError('Key %s not found in vault' % key)
```

**Pull request merged**
